#!/usr/bin/env bash
#
# Generates NATS operator + account keys and writes a ready-to-use .env file.
# Run this once before `docker compose up`.
#
# Prerequisites: nsc (brew install nats-io/nats-tools/nsc)
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/.env"
NSC_STORE="$SCRIPT_DIR/.nsc-store"

echo "=== NATS JWT Auth — Local Dev Setup ==="
echo ""

# Check nsc
if ! command -v nsc &>/dev/null; then
  echo "ERROR: nsc not found. Install it:"
  echo "  brew tap nats-io/nats-tools && brew install nats-io/nats-tools/nsc"
  exit 1
fi

# Clean slate for reproducible setup
if [ -d "$NSC_STORE" ]; then
  echo "Removing old NSC store at $NSC_STORE..."
  rm -rf "$NSC_STORE"
fi

echo "Creating NATS operator + account..."
echo ""

# Point nsc at our local store
nsc env --store "$NSC_STORE" >/dev/null 2>&1

# Create operator
nsc add operator --name localdev --sys 2>&1 | sed 's/^/  /'
nsc env -o localdev >/dev/null 2>&1

# Create account
nsc add account --name chatapp 2>&1 | sed 's/^/  /'

# Extract values
OPERATOR_JWT=$(nsc describe operator --raw 2>/dev/null)
ACCOUNT_JWT=$(nsc describe account chatapp --raw 2>/dev/null)
ACCOUNT_PUB_KEY=$(nsc describe account chatapp 2>/dev/null | grep "Account ID" | awk -F'|' '{gsub(/[ \t]/, "", $3); print $3}')
SYS_JWT=$(nsc describe account SYS --raw 2>/dev/null)
SYS_PUB_KEY=$(nsc describe account SYS 2>/dev/null | grep "Account ID" | awk -F'|' '{gsub(/[ \t]/, "", $3); print $3}')

# Find account seed file — nsc stores seeds under ~/.local/share/nats/nsc/keys/
ACCOUNT_SEED=""
for dir in "$HOME/.local/share/nats/nsc/keys/keys" "$NSC_STORE"; do
  SEED_FILE=$(find "$dir" -name "${ACCOUNT_PUB_KEY}.nk" 2>/dev/null | head -1)
  if [ -n "$SEED_FILE" ]; then
    ACCOUNT_SEED=$(cat "$SEED_FILE")
    break
  fi
done

if [ -z "$ACCOUNT_SEED" ]; then
  echo "ERROR: Could not find account seed file for ${ACCOUNT_PUB_KEY}"
  exit 1
fi

echo ""
echo "  Operator JWT:       ${OPERATOR_JWT:0:50}..."
echo "  Account Public Key: $ACCOUNT_PUB_KEY"
echo "  Account JWT:        ${ACCOUNT_JWT:0:50}..."
echo "  Account Seed:       ${ACCOUNT_SEED:0:12}..."
echo ""

# Write .env
cat > "$ENV_FILE" <<EOF
# Generated by setup.sh — do not commit this file
# Regenerate with: ./setup.sh

# === Keycloak (local dev) ===
OIDC_ISSUER_URL=http://localhost:9090/realms/chatapp
OIDC_AUDIENCE=nats-chat

# === NATS ===
NATS_ACCOUNT_SEED=${ACCOUNT_SEED}
NATS_ACCOUNT_PUBLIC_KEY=${ACCOUNT_PUB_KEY}
NATS_ACCOUNT_JWT=${ACCOUNT_JWT}
NATS_OPERATOR_JWT=${OPERATOR_JWT}

# === Auth Service ===
PORT=8080
NATS_JWT_EXPIRY=1h
EOF

# Write nats.conf with baked-in values (NATS doesn't support env vars in map keys)
NATS_CONF="$SCRIPT_DIR/nats.conf"
cat > "$NATS_CONF" <<EOF
# Generated by setup.sh — do not commit this file
# Regenerate with: ./setup.sh

port: 4222
http_port: 8222

operator: ${OPERATOR_JWT}

resolver: MEMORY

resolver_preload {
  ${ACCOUNT_PUB_KEY}: ${ACCOUNT_JWT}
  ${SYS_PUB_KEY}: ${SYS_JWT}
}

websocket {
  port: 9222
  no_tls: true
}
EOF

echo "Wrote $ENV_FILE"
echo "Wrote $NATS_CONF"
echo ""
echo "=== Ready! Run these commands: ==="
echo ""
echo "  # 1. Start Keycloak + NATS"
echo "  cd $SCRIPT_DIR"
echo "  docker compose up -d"
echo ""
echo "  # 2. Wait for Keycloak to be ready (~30-60s)"
echo "  docker compose logs -f keycloak  # watch for 'Listening on'"
echo ""
echo "  # 3. Start the auth service (on host, not Docker)"
echo "  cd $SCRIPT_DIR"
echo "  source .env && go run ../../cmd/server"
echo ""
echo "  # 4. (Optional) Start the frontend"
echo "  cd ../../example/frontend && npm install && npm run dev"
echo ""
echo "  ──────────────────────────────────────"
echo "  Keycloak Admin:   http://localhost:9090  (admin / admin)"
echo "  Auth Service:     http://localhost:8080/health"
echo "  NATS Monitoring:  http://localhost:8222"
echo "  NATS WebSocket:   ws://localhost:9222"
echo "  ──────────────────────────────────────"
echo ""
echo "  Test users: testuser/testuser  alice/alice"
echo ""
